version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/lib/shift-orcz"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
